@Library('safir_shared_library') _

pipeline {
    agent none
    stages {
        stage('On build slaves') {
            steps {
                parallelRunOnNodes { nodeLabel ->
                    script {
                        //run on all slaves
                        utils.runCommand(command: "pip install --user --upgrade psutil")

                        //run on only build slaves
                        if (nodeLabel.contains("-build")) {
                            utils.runCommand(command: "pip install --user --upgrade conan")
                            utils.runCommand(command: "pip install --user --upgrade websockets")
                            utils.runCommand(command: "conan remove --locks")
                            utils.runCommand(command: "conan remove -f '*'")
                        }
                    }
                }
            }
        }
    }
}
