@Library('safir_shared_library') _

pipeline {
    parameters {
        booleanParam(name: 'REMOVE_ALL_CONAN_PACKAGES',
                     defaultValue: true,
                     description: 'Remove all conan packages?')

    }
    agent none


    environment {
        PIP_BREAK_SYSTEM_PACKAGES=1
    }

    stages {
        stage ("Clean and Reboot"){
            steps {
                parallelRunOnNodes { nodeLabel ->
                    checkout scm
                    script {
                        //run on only build slaves
                        if (nodeLabel.contains("-build")) {
                            utils.runPython(command: "conan remove --locks",
                                            requirements: "clean_and_reboot_slaves/requirements.txt")
                            if (params.REMOVE_ALL_CONAN_PACKAGES) {
                                utils.runPython(command: 'conan remove -f "*"',
                                                requirements: "clean_and_reboot_slaves/requirements.txt")
                            }
                        }

                        //The checkout gets the whole repo, so we need to provide the path relative the repo root.
                        utils.runPython(script: "clean_and_reboot_slaves/clean_slave.py",
                                        requirements: "clean_and_reboot_slaves/requirements.txt")

                        //Remove conan2 packages (this has different requirements, so we do it after)
                        if (nodeLabel.contains("-build") && params.REMOVE_ALL_CONAN_PACKAGES) {
                                utils.runPython(command: 'conan remove -c "*/*"',
                                                requirements: "clean_and_reboot_slaves/requirements2.txt")
                        }

                        //Reboot in 60 seconds
                        if (utils.betterIsUnix()) {
                            utils.runCommand(command: "sudo shutdown -r +1")
                        }
                        else {
                            utils.runCommand(command: "shutdown -r -t 60")
                        }

                        utils.markNodeOffline(nodeLabel, "Rebooting")
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                sleep (180) //Nodes should be rebooting by now
                utils.markAllNodesOnline()
            }
        }
    }
}
